name: creatingthecarlsons
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50279
title: creating the carlsons
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0c'
    - '#ffffff'
    - '#9399a4'
    - '#e44e5c'
    - '#ff8672'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
